const PROTOCOL = 'http://'
const SERVER_ADDRESS = `localhost`
const SERVER_PORT_NUM = 3000

const URL_USER_LOGIN_SIGN_UP = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/users/signup`
const URL_USER_LOGIN_SIGN_IN = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/users/signin` 
const URL_SAVE_PROJECT = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/projects/save`
const URL_PROJECT_DELETE = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/projects/delete`
const URL_PROJECT_GET_CONTENT = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/projects/getContent`

export {
  PROTOCOL,
  SERVER_ADDRESS,
  SERVER_PORT_NUM,
  URL_USER_LOGIN_SIGN_UP,
  URL_USER_LOGIN_SIGN_IN,
  URL_SAVE_PROJECT,
  URL_PROJECT_DELETE,
  URL_PROJECT_GET_CONTENT,
}