const PROTOCOL = 'http://'
const SERVER_ADDRESS = `45.63.119.250`
//const SERVER_ADDRESS = `127.0.0.1`
const SERVER_PORT_NUM = 3000

const SERVER_ADDRESS_APP1 = `212.64.12.39`
const SERVER_PORT_NUM_APP1 = 80

const URL_USER_LOGIN_SIGN_UP = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/users/signup`
const URL_USER_LOGIN_SIGN_IN = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/users/signin` 
const URL_USER_LOGIN = `${PROTOCOL}${SERVER_ADDRESS_APP1}:${SERVER_PORT_NUM_APP1}/build_login/` 
const URL_USER_COOKIE_LOGIN = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/users/cookieLogin`
const URL_SAVE_PROJECT = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/projects/save`
const URL_SHARE_PROJECT_TOGGLE = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/projects/toggleShare`
const URL_PROJECT_DELETE = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/projects/delete`
const URL_PROJECT_GET_SHARED = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/projects/getSharedProjects`
const URL_PROJECT_GET_CONTENT = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/projects/getContent`
const URL_PROJECT_UPDATE_DESCRIPTION = `${PROTOCOL}${SERVER_ADDRESS}:${SERVER_PORT_NUM}/projects/updateDescription` 

export {
  PROTOCOL,
  SERVER_ADDRESS,
  SERVER_PORT_NUM,
  URL_USER_LOGIN_SIGN_UP,
  URL_USER_LOGIN_SIGN_IN,
  URL_USER_LOGIN,
  URL_USER_COOKIE_LOGIN,
  URL_SAVE_PROJECT,
  URL_SHARE_PROJECT_TOGGLE,
  URL_PROJECT_DELETE,
  URL_PROJECT_GET_SHARED,
  URL_PROJECT_GET_CONTENT,
  URL_PROJECT_UPDATE_DESCRIPTION,
}